example/build/lib.js, lib/ImageOverlay.js, lib/Map.js, lib/Rectangle.js, lib/types/bounds.js, src/ImageOverlay.js, src/Map.js, src/Rectangle.js, src/types/bounds.js
Adds a new PropTypes type. ImageOverlay, Map and Reactangle allow a `bounds` property to be set whose value might either be an array of LatLng values or (and that's fixed by this pull request) an instance of Leaflet.LatLngBounds.
Previous implementation caused warnings on the console if a (valid) LatLngBounds instance was passed.
See http://leafletjs.com/reference.html#map-maxbounds
=> Add new prop type for bounds

example/build/lib.js, lib/Popup.js, src/Popup.js
This commit fixes an issue when popups could suddenly lose their options. That's because `popupContainer.bindPopup()` actually creates a new popup. Now the popup options are passed to `bindPopup`.
=> Fix popup loosing options on `popupContainer.bindPopup()`

src/Map.js
For React projects that are starting to adopt the inclusion of CSS in components, this change would be super helpful.
[example](https://github.com/troutowicz/geoshare/blob/css-in-js/app/components/App.jsx#L40)
=> Allow inline styling for Map comp

src/index.js
PopupContainer will export PopupContainer instead of Popup.
It actually gave me a hard time to figure out why my own Leaflet elements inherited from PopupContainer did not render. It turned out that the PopupContainer was exporting Popup instead. After fixing this everything worked as expected.
=> Fixed exporting of PopupContainer

example/events.js, example/simple.js, example/vector-layers.js, gulpfile.js, src/MapComponent.js
It fixes an issue when a layer component had a length attribute, lodash see the object as an array so the events couldn't be extracted.
Also fix nested simple quote issues after a blind double to simple quote replace.
I didn't included the generated files.
=> Fix ignored events when there is an attribute named "length" in a layer

.gitignore, bower.json
I use this library in conjunction with the [Rails Assets proxy](https://rails-assets.org/) to use bower dependencies in my gem file. Unfortunately this library does not provide a bower.json file and is therefore not part of the bower registry.
This PR adds a `bower.json` file. The registration must be done by the author.
=> Add bower.json file

README.md, src/AttributionControl.js, src/LayersControl.js, src/ScaleControl.js, src/index.js
Filling out some of the missing controls in #87.
I've done some basic testing on Attribution and Scale. The Layers control gets placed on the map, but I'm not sure how to correctly pass a base layer reference from a, say, `TileLayer` component into the Layers control.
=> Add other controls in v1 TODO

src/CanvasTileLayer.js, src/Circle.js, src/CircleMarker.js, src/GeoJson.js, src/ImageOverlay.js, src/LayerGroup.js, src/Map.js, src/MapLayer.js, src/Marker.js, src/MultiPolygon.js, src/MultiPolyline.js, src/Polygon.js, src/Polyline.js, src/Rectangle.js, src/TileLayer.js, src/WMSTileLayer.js, src/types/index.js, src/types/layerContainer.js
**Edit (2016-04-02):**
Split the LayersControl code into a new branch, rebased to d057013, removed the built files, and filterd out the `layerContainer` prop everywhere from the layer options objects (same as the `map` prop).
~~This is a two-part PR.~~
**The first part is the `layerContainer` prop.**
Until now a `MapLayer` could receive either a `map` or a `layerGroup` prop. With this PR a `MapLayer` always receives both the `map` and the `layerContainer` props. The `map` is always the same, and the `layerContainer` is either the `map` or the old `layerGroup`.
This way all the map layers have access to the root `Map` instance, and other kind of layer containers can be introduced less intrusively.
~~**The second is a LayersControl implementation for #87** that makes use of the …
=> Layer container interface

__tests__/LayersControl.js, lib/LayersControl.js, src/LayersControl.js
Map is not passed to children of LayersControl. This breaks the behaviour defined for custom components.
Could not get `unmock` to work properly and it always passed the test due to ChildComponent not being rendered. My failed attempt at unmock looked like this,
```js
jest.dontMock('../src/LayersControl');
jest.dontMock('../src/Map');
jest.dontMock('../src/MapControl');
jest.dontMock('../src/types/bounds');
jest.dontMock('../src/types/children');
jest.dontMock('../src/types/index');
jest.dontMock('../src/types/latlng');
jest.dontMock('../src/types/controlPosition');
jest.dontMock('../src/types/layerContainer');
```
=> LayersControl does not pass map props to children

example/components/draggable-marker.js, example/components/index.js, src/Marker.js
Toggling draggable status is a useful part of leaflet markers, it is nice to have it exposed via props on the Marker component. Usage example included.
=> Add dynamic draggable props to Marker

src/MapControl.js
In Leaflet 1.0 `Control` doesn't have `removeFrom` anymore, only `remove`.
=> [leaflet 1.0] Change `removeFrom` to `remove` for `MapControl`

docs/Components.md, src/Map.js
=> Support "flyTo"

src/MultiPolygon.js
Like 'Polygon' already allows passing array of arrays to make holes, also
MultiPolygon should allow it. Even though not read in Leaflet
MultiPolygon documentation, it supports it because Polygon supports it.
=> Updated MultiPolygon 'polygons' prop to allow polygons with holes

src/ImageOverlay.js
=> ImageOverlays can be linked to Popups and Tooltips

src/MapComponent.js
Fixes the following when `myCondition` is `falsey`.
`<MapComponent onClick={myCondition ? myCallback : null} />`
=> Only extract leaflet events for prop keys when callback exists

src/ImageOverlay.js
Looks like this was just an oversight.
The additional `latLngBounds` cast is necessary because the props can contain a 2-D Array, but `setBounds` expects a `Bounds` object with `_bounds.getNorthWest` etc.
=> Allow ImageOverlay bounds to be changed on the fly

docs/Plugins.md
This is a plugin for https://github.com/nickpeihl/leaflet-sidebar-v2, which is a nice collapsable floating sidebar with tabs.  I originally attempted this by wrapping the original plugin, but it does a lot of DOM manipulation and was fundamentally at odds with React, at least how I envisaged it.  So, I render all the markup from scratch and just use the sidebar-v2 CSS, but that seems to work quite well.
=> Add react-leaflet-sidebarv2 plugin to the list

.travis.yml, rollup.config.js
Fix #375
I added node 6 back to travis (this was the issue I disabled it for a while back). It is not actually necessary, but a lot of people are still using node 6, so this will prevent issues like #375.
I don’t know why `prettier/prettier` is asking for a comma there…
=> Remove comma that causes a syntax error in node 6

__tests__/Marker.js, __tests__/Popup.js, docs/Components.md, docs/Getting started.md, example/components/animate.js, example/components/bounds.js, example/components/custom-component.js, example/components/draggable-marker.js, example/components/events.js, example/components/layers-control.js, example/components/other-layers.js, example/components/pane.js, example/components/simple.js, example/components/tooltip.js, example/components/vector-layers.js, example/components/video-overlay.js, example/components/viewport.js, example/components/wms-tile-layer.js, example/components/zoom-control.js, example/umd.html
Using the Geolocation API in current browsers requires a secure context [0].
I updated the documentation and examples to load the map tiles over secure connections, to prevent possible problems.
[0]https://developer.mozilla.org/en-US/docs/Web/API/Geolocation
=> use https for tiles server

src/WMSTileLayer.js
See PaulLecam/react-leaflet#404.  Initial values were being removed
from the parameters passed to the leaflet element when it was first
created; later updates were still correctly applied.
=> Don't remove zIndex/opacity from initial WMS props

src/LayersControl.js
Upgrading to flow-bin@0.59.0 yields the following errors:
```
$ flow
Error: src/LayersControl.js:105
105:   addLayer(layer) {
^^^^^ parameter `layer`. Missing annotation
Error: src/LayersControl.js:115
115:   addLayer(layer) {
^^^^^ parameter `layer`. Missing annotation
```
This commit adds some missing annotations, satisfying the beast.
=> Add types to satisfy flow 59

src/Popup.js
Fixes https://github.com/PaulLeCam/react-leaflet/issues/422
----
Manual :(
Since we mock out `Leaflet.Popup` I was unable to write a test case. Open to suggestions!
=> Update Popup element only after render is complete

src/FeatureGroup.js, src/LayersControl.js
Upgrading to flow-bin@0.66.0 yields the following errors:
```> flow check
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/FeatureGroup.js:19:30
Could not decide which case to select. Since case 1 [1] may work but if it
doesn't case 5 [2] looks promising too. To fix add a type annotation to
children [3] or to layer [4].
src/FeatureGroup.js
16│ }
17│
18│ export default class FeatureGroup extends Path<LeafletElement, Props> {
19│   static childContextTypes = {
[3] 20│     children: children,
21│     layerContainer: layerContainer,
[4] 22│     popupContainer: layer,
23│   }
24│
25│   getChildContext(): ChildContext {
26│     return {
/private/tmp/flow/flowlib_493edf3/react.js
[2] 74│   static childContextTypes: any;
src/Path.js
[1] 38│   static childContextTypes = {
39│ …
```
=> Add types to satisfy flow-bin 0.66

package.json
Following the latest version, I've been getting import unresolved errors when running eslint locally. 
```
error  Unable to resolve path to module 'react-leaflet'  import/no-unresolved
```
After checking `node_modules` I noticed that the `es` folder is being cleared out on publish. I've simply added this to the files array.
=> 🚧 Fix - added es folder to files array in package.json

docs/components.md, src/Map.js
Currently, if an end user changes any of the top level handler options in the `Map` component the associated Leaflet handlers aren't updated when the component updates. 
In our own use case, we switch on and off the `doubleClickZoom` functionality when switching between various modes in our application. I noticed the other handlers were missing so I've included these.
=> Feature - Support Map handlers when component updated

src/Map.js
This prevents an infinite loop error that I experienced on my React app, apparently the events were being fired even after the DOM element was removed
=> Remove event listeners

src/DivOverlay.js, src/Popup.js, src/Tooltip.js
This makes it possible to natively pass context trough to the subtree that is rendered inside the popup.
=> Use createPortal for rendering DivOverlays

docs/plugins.md
react-leaflet-nmscale is nautical mile scale component.
works only with ^2.0.0-beta.1 || ^2.0.0
=> Add react-leaflet-nmscale to plugins list

docs/plugins.md
[react-leaflet-freedraw](https://github.com/elangobharathi/react-leaflet-freedraw) is a plugin that integrates [Leaflet.FreeDraw](https://github.com/Wildhoney/Leaflet.FreeDraw) library.
=> Add react-leaflet-freedraw to plugins list

docs/intro.md
1. Updated lifecycle overview to explain that child components create their Leaflet element in the `constructor()` (not `componentWillUpdate()`, which is no longer used).
2. Added an additional step explaining that the component adds its Leaflet element to the map in `componentDidMount()`.
=> Modified "Lifecycle process" overview in intro.md

docs/plugins.md
I've built a plugin that wraps https://github.com/mylen/leaflet.TileLayer.WMTS behaviour. I think it could be useful to have in the plugins page.
Thanks for react-leaflet by the way!
=> Add react-leaflet-wmts to plugins page

.babelrc
Build with ESM versions of babel runtime functions. Results in slightly smaller app bundle size.
docs:
https://babeljs.io/docs/en/babel-plugin-transform-runtime#useesmodules
=> Use ESM babel runtime functions for jsnext build

docs/plugins.md
`react-leaflet-control` was updated 5 months ago and is compatible with react-leaflet v2.
=> Update react-leaflet-control compatibility status

docs/plugins.md
I was facing some issues while trying to use react-leaflet-div-icon and react-leaflet-heatmap-layer with react-leaflet, and then I realized that react-leaflet-div-icon [doesn't support react-leaflet v2.0](https://github.com/jgimbel/react-leaflet-div-icon/issues/20) and [react-leaflet-heatmap-layer does](https://github.com/OpenGov/react-leaflet-heatmap-layer/blob/master/CHANGELOG.md#200-release).
=> Updates third party compatibility docs

src/LayerGroup.js
While working with react-leaflet LayerGroup, I noticed that the annotations were not being passed correctly to the underlying Leaflet LayerGroup.  
None of the options were being passed through correctly, as they're being passed in as the layers instead of the options.
=> Passing LayerGroup options to the correct leaflet LayerGroup parameter

docs/custom-components.md, docs/hooks.md, package.json, src/context.js, src/index.js, website/sidebars.json
Implemented `useLeaflet` hook.
Example:
```javascript
const MyComponent = (props) => {
const { map } = useLeaflet()
return <>...</>
}
```
closes #539
=> 'useLeaflet' hook

docs/components.md, src/Map.js
Add leaflet [ZoomPanOptions](https://leafletjs.com/reference-1.5.0.html#zoom/pan-options) and [FitBOundsOptions](https://leafletjs.com/reference-1.5.0.html#fitbounds-options) to Map component props.
The only missing props where the [PanOptions](https://leafletjs.com/reference-1.5.0.html#pan-options): `duration`, `easeLinearity` and `noMoveStart`.
Updated documentation in  `/docs/components.md`.
=> Add ZoomPanOptions and FitBoundsOptions to Map component

src/Map.js
The `doubleClickZoom` option also supports the `"center"` setting as e.g. `scrollWheelZoom` does. This patch adds the missing support for it.
=> Add support for doubleClickZoom option's "center" setting

docs/plugins.md
react-leaflet-bing is now obsolete. The new package name is react-leaflet-bing-v2
=> new package for react-leaflet-bing

docs/plugins.md
the react-leaflet-google is obsolete. Now, they can use react-leaflet-google-v2 package.
=> update react-leaflet-google plugin

docs/plugins.md
Recent part-wrap of Leaflet.Geodesic to React.
Although it still has only GeodesicLine, I think it would be usefull to people that might need it.
=> Add react-leaflet-geodesic to plugins.md

.babelrc
This sets used runtime version for @babel/transform-runtime.
https://babeljs.io/docs/en/babel-plugin-transform-runtime#version
It results in a smaller bundle, as transform can depend on newer features be present on runtime.
Before:
```
97810 react-leaflet.js
42915 react-leaflet.min.js
```
After:
```
87280 react-leaflet.js
36061 react-leaflet.min.js
```
By using .babelrc.js, the version could come from package.json like this: 
```javascript
const ENV = process.env.BABEL_ENV || process.env.NODE_ENV || 'development';
const pkg = require('./package.json');
const runtimeVersion = pkg.dependencies['@babel/runtime'];
```
But probably the need for version field is removed in Babel 8 anyway.
=> Set babel runtime version to make smaller bundle

docs/components.md, docs/events.md, website/versioned_docs/version-v2/components.md, website/versioned_docs/version-v2/events.md
=> bump-reference-version

example/components/svg-overlay.js, src/SVGOverlay.js, src/types.js
Simply the suggestions in #702 as an actual pull request.
- Add `viewBox` property.
- Add `preserveAspectRatio` property (it works hands in hands with `viewBox`).
- Set the `xmlns` attribute. Not *required* but cleaner and matches leaflet.js documentation.
Fixes #702.
=> Add viewBox and preserveAspectRatio props to SVGOverlay element

docs/components.md
Sections (`##`) are not clearly defined when rendered at the website (https://react-leaflet.js.org/docs/en/components), and I think such text markup/splitting helps when reading API docs. That's all proposing here.
=> Add <hr> lines to mark section limits

packages/react-leaflet/package.json, packages/react-leaflet/rollup.config.js, yarn.lock
This switches rollup to use terser instead of uglifyjs.
The PR targets V3 branch.
Terser allows es2015+ syntax in input source code.
Without this the babel needs to transpile code down to es5, which it is currently doing.
=> Minify umd bundle using terser

.babelrc
This drops support for IE.
This results in a following current (but moving) browser support:
```json
{
"android": "81",
"chrome": "81",
"edge": "81",
"firefox": "77",
"ios": "13.3",
"node": "12.18.2",
"opera": "68",
"safari": "13",
"samsung": "11.1"
}
```
The issue #698 noted that support for IE will be dropped in v3. However the babel config is using "last 2 versions" which includes both IE 10 and 11.
I think it would be better to explicitly declare supported browsers:
```json
"browsers": [
"Chrome >= 73",
"ChromeAndroid >= 73",
"Firefox >= 68",
"Edge >= 18",
"Safari >= 12",
"Samsung >= 10",
"iOS >= 12"
]
```
Without explicit browser support almost all users of react-leaflet need to transpile down to their set of browsers.
=> Drop support for IE in v3

.babelrc, package.json, packages/core/package.json, packages/react-leaflet/package.json, packages/react-leaflet/rollup.config.js, yarn.lock
This PR removes runtime transform and polyfilling from babel config.
1. The runtime and polyfills are not needed as only last 2 versions of browsers are supported
2. It saves bundle size. The UMD bundle is now only 11kB, down from 44kB.
The docusaurus build seems to be failing. It also fails for me on branch 'next', so it should not be caused by this PR.
=> Drop @babel/runtime and polyfilling

packages/react-leaflet/package.json, packages/react-leaflet/rollup.config.js, yarn.lock
This upgrades rollup plugins to more recent versions.
Just to keep them up to date as they are now released with namespaced names instead.
=> Upgrade rollup plugins

packages/website/docs/api-map.md
I'm founded an incorrect example in documentation for `next` (v3) version of library when I research examples.
Before:
```
<MapConsumer>
...
<MapConsumer>  {/* Example without slash */}
```
After:
```
<MapConsumer>
...
</MapConsumer> {/* Example with slash */}
```
=> Fix: Fixed incorrect react example

package.json, yarn.lock
This adds react 17 to react-leaflet@^2 peerDependencies.
To allow react version overlap with the react-leaflet@^3.
=> Allow react 17 in peerDependencies

packages/website/docs/api-components.md
This adds documentation for the GeoJSON showing that it has `pathOptions` prop, same as Rectangle et al.
~It's marked Mutable like for the other Components and changing it is actually delegated to the leaflet object, however it does not work as it needs [`resetStyle()`](https://leafletjs.com/reference-1.7.1.html#geojson-resetstyle) to be called.~
~Setting a different `color` or `weight` via `pathOptions` on a `<Rectangle.../>` did neither work for me, so I wonder if it's a bug or if is intended but the documentation is misleading.~
Edit: Nevermind the update issues. It's updating. I was setting only the sub-property not the whole pathOptions. My problem can be reproduced with the third case within in https://codesandbox.io/s/xenodochial-proskuriakova-pytgj?file=/src/Map.js:8695-8722 and …
=> Document pathOptions for GeoJSON

README.md, packages/website/docs/api-components.md, packages/website/docs/core-architecture.md, packages/website/docs/example-animated-panning.md, packages/website/docs/example-draggable-marker.md, packages/website/docs/example-events.md, packages/website/docs/example-external-state.md, packages/website/docs/example-layers-control.md, packages/website/docs/example-map-placeholder.md, packages/website/docs/example-other-layers.md, packages/website/docs/example-panes.md, packages/website/docs/example-popup-marker.md, packages/website/docs/example-react-control.md, packages/website/docs/example-svg-overlay.md, packages/website/docs/example-tooltips.md, packages/website/docs/example-vector-layers.md, packages/website/docs/example-view-bounds.md, packages/website/docs/start-setup.md, packages/website/src/pages/index.js
I updated a lot of attribution links which still used insecure http. Additionally the attribution links were updated to the current OSM recommendation as shown on this page: https://www.openstreetmap.org/copyright
Updated some other URLs from http to https.
=> fix: HTTP urls updated to https; OSM attribution link updated

packages/react-leaflet/src/Tooltip.tsx
`TooltipProps` had `position` defined, but it never functioned, since `L.Tooltip` does not accept `position` option. So we need to `setLatLng` manually when opening the popup.
=> Fix tooltip position prop

packages/website/docs/start-installation.mdx, packages/website/docs/start-introduction.md
Fix typos in getting started docs
=> Fix typos in getting started docs

packages/core/src/element.ts
- WAS: createElement() factory called at every render, therefore nullifying any benefits of using MutableRefObject
- NOW: createElement() factory called only if useRef() does not hold an already cached element object
=> Fixing useRef() usage in createElementHook to prevent unnecessary Leaflet object creation

packages/core/src/index.ts, packages/core/src/tile-layer.ts, packages/react-leaflet/__tests__/TileLayer.tsx, packages/react-leaflet/__tests__/__snapshots__/TileLayer.tsx.snap, packages/react-leaflet/src/TileLayer.tsx
Hi! I have a use case where I change the URL of a tile layer at runtime to change out query parameters depending on user interactions. With core Leaflet, I use the `setUrl()` method. I think it would make sense to expose this in react-leaflet.
=> Support changing `url` in TileLayer
